name: Automated Cold Storage to GDrive

on:
  push:
    branches: [ main, master ] # Berjalan jika ada update di branch main atau master
  workflow_dispatch:          # Memungkinkan tombol "Run workflow" manual

jobs:
  backup-to-gdrive:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Mengambil seluruh riwayat jika diperlukan

      - name: Install Rclone
        run: sudo apt-get install -y rclone

      - name: Configure Rclone
        run: |
          mkdir -p ~/.config/rclone
          echo "${{ secrets.RCLONE_CONF }}" > ~/.config/rclone/rclone.conf

      - name: Sync to Google Drive
        run: |
          rclone sync . "Gdrive:GitHub_Backup/${{ github.event.repository.name }}" --exclude ".git/**" --verbose
